inherit_from: .rubocop_todo.yml

# .rubocop.yml
AllCops:
  Exclude:
    - spec/spec_helper.rb
    - Gemfile
    - Gemfile.lock
  NewCops: disable
Style/Documentation:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - spec/**/*